services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    env_file:
      - ../.env
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    
    ports:
      - ${RABBIT_PORT}:15672
      - ${AMQP_PORT}:5672
    command: >
      bash -c "
      rabbitmq-server & 
      sleep 10 && 
      rabbitmqctl list_users | grep -q ${RABBIT_USER} || (
        rabbitmqctl add_user ${RABBIT_USER} ${RABBIT_PASSWORD} &&
        rabbitmqctl set_user_tags ${RABBIT_USER} administrator &&
        rabbitmqctl set_permissions -p / ${RABBIT_USER} '.*' '.*' '.*'
      ) &&
      wait
      "