services:
  django-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "${API_PORT}:8000"
    command: ["sh", "/app/entrypoint.sh"]
    env_file:
      - ../.env
    volumes:
      - ../.:/app/
    depends_on:
      - postgres
