services:
  django-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "${API_PORT}:8000"
    command: >
      bash -c "poetry run python telegram_auth/manage.py runserver 0.0.0.0:${API_PORT}"
    env_file:
      - ../.env
    volumes:
      - ../.:/app/
    depends_on:
      - postgres
