services:
  django-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "${API_PORT}:8000"
    command: ["sh", "/app/entrypoint.sh"]
    env_file:
      - ../.env
    volumes:
      - ../.:/app/
    depends_on:
      - postgres

  celery:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: celery
    command: ["sh", "-c", "sleep 10 && poetry run celery -A telegram_auth.telegram_auth.celery worker --loglevel=info"]
    env_file:
      - ../.env
    volumes:
      - ../.:/app/
    depends_on:
      - rabbitmq
      - django-app
      - postgres
