services:
  telegram-bot:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: telegram-bot
    command: >
      bash -c "poetry run python bot/start.py"
    env_file:
      - ../.env
    depends_on:
      - rabbitmq
