# Generated by Django 5.1.4 on 2024-12-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_usertoken_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
