# Generated by Django 5.1.4 on 2024-12-21 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='telegram_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL),
        ),
    ]
